// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function AddCustomClip(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCustomClip'](arg1, arg2, arg3);
}

export function AddOverlayClip(arg1) {
  return window['go']['main']['App']['AddOverlayClip'](arg1);
}

export function AddOverlayImage(arg1) {
  return window['go']['main']['App']['AddOverlayImage'](arg1);
}

export function CancelGeneration(arg1) {
  return window['go']['main']['App']['CancelGeneration'](arg1);
}

export function CancelOverlayRender(arg1) {
  return window['go']['main']['App']['CancelOverlayRender'](arg1);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ConfigureWorker() {
  return window['go']['main']['App']['ConfigureWorker']();
}

export function CreateOverlayFromClip(arg1) {
  return window['go']['main']['App']['CreateOverlayFromClip'](arg1);
}

export function CreateOverlayProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateOverlayProject'](arg1, arg2, arg3);
}

export function DeleteAllSource() {
  return window['go']['main']['App']['DeleteAllSource']();
}

export function DeleteClips(arg1) {
  return window['go']['main']['App']['DeleteClips'](arg1);
}

export function DeleteOverlayCover(arg1) {
  return window['go']['main']['App']['DeleteOverlayCover'](arg1);
}

export function DeleteOverlayImage(arg1) {
  return window['go']['main']['App']['DeleteOverlayImage'](arg1);
}

export function DeleteOverlayProject(arg1) {
  return window['go']['main']['App']['DeleteOverlayProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSourceVideo(arg1) {
  return window['go']['main']['App']['DeleteSourceVideo'](arg1);
}

export function DeleteVideos(arg1) {
  return window['go']['main']['App']['DeleteVideos'](arg1);
}

export function DownloadAllAsZip(arg1) {
  return window['go']['main']['App']['DownloadAllAsZip'](arg1);
}

export function ExportClips(arg1, arg2) {
  return window['go']['main']['App']['ExportClips'](arg1, arg2);
}

export function FindMoreClips(arg1) {
  return window['go']['main']['App']['FindMoreClips'](arg1);
}

export function GenerateClips(arg1, arg2) {
  return window['go']['main']['App']['GenerateClips'](arg1, arg2);
}

export function GeneratePreview(arg1) {
  return window['go']['main']['App']['GeneratePreview'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetClipFaces(arg1) {
  return window['go']['main']['App']['GetClipFaces'](arg1);
}

export function GetClipOutputPath(arg1) {
  return window['go']['main']['App']['GetClipOutputPath'](arg1);
}

export function GetClipThumbnails(arg1, arg2) {
  return window['go']['main']['App']['GetClipThumbnails'](arg1, arg2);
}

export function GetClipWaveform(arg1) {
  return window['go']['main']['App']['GetClipWaveform'](arg1);
}

export function GetClips(arg1) {
  return window['go']['main']['App']['GetClips'](arg1);
}

export function GetDeletePreview(arg1) {
  return window['go']['main']['App']['GetDeletePreview'](arg1);
}

export function GetFaceTrack(arg1) {
  return window['go']['main']['App']['GetFaceTrack'](arg1);
}

export function GetGallery() {
  return window['go']['main']['App']['GetGallery']();
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetOverlayProject(arg1) {
  return window['go']['main']['App']['GetOverlayProject'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSetupProgress() {
  return window['go']['main']['App']['GetSetupProgress']();
}

export function GetStorageBreakdown() {
  return window['go']['main']['App']['GetStorageBreakdown']();
}

export function GetThread(arg1) {
  return window['go']['main']['App']['GetThread'](arg1);
}

export function GetTranscriptRange(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTranscriptRange'](arg1, arg2, arg3);
}

export function GetVideoPath(arg1) {
  return window['go']['main']['App']['GetVideoPath'](arg1);
}

export function IsLicenseValid() {
  return window['go']['main']['App']['IsLicenseValid']();
}

export function IsSetupComplete() {
  return window['go']['main']['App']['IsSetupComplete']();
}

export function ListLibraryVideos() {
  return window['go']['main']['App']['ListLibraryVideos']();
}

export function ListOverlayImages() {
  return window['go']['main']['App']['ListOverlayImages']();
}

export function ListOverlayProjects() {
  return window['go']['main']['App']['ListOverlayProjects']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListVideos() {
  return window['go']['main']['App']['ListVideos']();
}

export function GetVideo(arg1) {
  return window['go']['main']['App']['GetVideo'](arg1);
}

export function ListProjectsByVideo(arg1) {
  return window['go']['main']['App']['ListProjectsByVideo'](arg1);
}

export function MakeMoreClips(arg1) {
  return window['go']['main']['App']['MakeMoreClips'](arg1);
}

export function OnFileDrop(arg1) {
  return window['go']['main']['App']['OnFileDrop'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PickOverlayClip() {
  return window['go']['main']['App']['PickOverlayClip']();
}

export function PickOverlayImage() {
  return window['go']['main']['App']['PickOverlayImage']();
}

export function PreviewReframe(arg1, arg2) {
  return window['go']['main']['App']['PreviewReframe'](arg1, arg2);
}

export function RedownloadDependency(arg1) {
  return window['go']['main']['App']['RedownloadDependency'](arg1);
}

export function RedownloadSource(arg1) {
  return window['go']['main']['App']['RedownloadSource'](arg1);
}

export function RegenerateCaption(arg1) {
  return window['go']['main']['App']['RegenerateCaption'](arg1);
}

export function RemoveClip(arg1) {
  return window['go']['main']['App']['RemoveClip'](arg1);
}

export function RenderOverlay(arg1) {
  return window['go']['main']['App']['RenderOverlay'](arg1);
}

export function RetrackFaces(arg1) {
  return window['go']['main']['App']['RetrackFaces'](arg1);
}

export function RetryClip(arg1) {
  return window['go']['main']['App']['RetryClip'](arg1);
}

export function RetryStep(arg1, arg2) {
  return window['go']['main']['App']['RetryStep'](arg1, arg2);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function RunSetup() {
  return window['go']['main']['App']['RunSetup']();
}

export function SaveCaption(arg1, arg2) {
  return window['go']['main']['App']['SaveCaption'](arg1, arg2);
}

export function SaveOverlayProject(arg1) {
  return window['go']['main']['App']['SaveOverlayProject'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetClipAspectRatio(arg1, arg2) {
  return window['go']['main']['App']['SetClipAspectRatio'](arg1, arg2);
}

export function SetClipCaptionOpts(arg1, arg2) {
  return window['go']['main']['App']['SetClipCaptionOpts'](arg1, arg2);
}

export function SetClipCaptionStyle(arg1, arg2) {
  return window['go']['main']['App']['SetClipCaptionStyle'](arg1, arg2);
}

export function SetClipTrackOpts(arg1, arg2) {
  return window['go']['main']['App']['SetClipTrackOpts'](arg1, arg2);
}

export function SetClipTrackTemplate(arg1, arg2) {
  return window['go']['main']['App']['SetClipTrackTemplate'](arg1, arg2);
}

export function SetOverlayCover(arg1, arg2) {
  return window['go']['main']['App']['SetOverlayCover'](arg1, arg2);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function TestProviderKey(arg1, arg2) {
  return window['go']['main']['App']['TestProviderKey'](arg1, arg2);
}

export function ToggleClip(arg1, arg2) {
  return window['go']['main']['App']['ToggleClip'](arg1, arg2);
}

export function UpdateClipTimestamp(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateClipTimestamp'](arg1, arg2, arg3);
}
