// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clip} from '../models';
import {setup} from '../models';
import {main} from '../models';
import {project} from '../models';
import {settings} from '../models';

export function ActivateLicense(arg1:string):Promise<void>;

export function AddCustomClip(arg1:string,arg2:number,arg3:number):Promise<clip.Clip>;

export function CancelGeneration(arg1:string):Promise<void>;

export function CheckDependencies():Promise<Array<setup.Dependency>>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ClearCache():Promise<number>;

export function ConfigureWorker():Promise<void>;

export function DeleteAllSource():Promise<number>;

export function DeleteClips(arg1:Array<string>):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteVideos(arg1:Array<string>):Promise<void>;

export function DownloadAllAsZip(arg1:string):Promise<string>;

export function ExportClips(arg1:Array<string>,arg2:main.ExportOpts):Promise<void>;

export function GenerateClips(arg1:string,arg2:Array<string>):Promise<void>;

export function GeneratePreview(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetClipFaces(arg1:string):Promise<Array<main.FaceSampleEntry>>;

export function GetClipOutputPath(arg1:string):Promise<string>;

export function GetClipThumbnails(arg1:string,arg2:number):Promise<Array<string>>;

export function GetClipWaveform(arg1:string):Promise<Array<number>>;

export function GetClips(arg1:string):Promise<Array<clip.Clip>>;

export function GetDeletePreview(arg1:Array<string>):Promise<main.DeletePreview>;

export function GetFaceTrack(arg1:string):Promise<Array<main.FaceFrame>>;

export function GetGallery():Promise<Array<clip.GalleryItem>>;

export function GetLicenseStatus():Promise<main.LicenseStatus>;

export function GetProject(arg1:string):Promise<project.Project>;

export function GetProviders():Promise<Array<main.Provider>>;

export function GetSettings():Promise<settings.Settings>;

export function GetSetupProgress():Promise<Array<setup.Dependency>>;

export function GetStorageBreakdown():Promise<main.Storage>;

export function GetThread(arg1:string):Promise<Array<main.ThreadStep>>;

export function GetTranscriptRange(arg1:string,arg2:number,arg3:number):Promise<Array<main.TranscriptSegment>>;

export function GetVideoPath(arg1:string):Promise<string>;

export function IsLicenseValid():Promise<boolean>;

export function IsSetupComplete():Promise<boolean>;

export function ListProjects():Promise<Array<project.Project>>;

export function OnFileDrop(arg1:Array<string>):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PreviewReframe(arg1:string,arg2:string):Promise<main.CropPlan>;

export function RedownloadDependency(arg1:string):Promise<void>;

export function RegenerateCaption(arg1:string):Promise<string>;

export function RemoveClip(arg1:string):Promise<void>;

export function RetrackFaces(arg1:string):Promise<void>;

export function RetryClip(arg1:string):Promise<void>;

export function RetryStep(arg1:string,arg2:string):Promise<void>;

export function RunCommand(arg1:string,arg2:string):Promise<main.CommandResult>;

export function RunSetup():Promise<void>;

export function SaveCaption(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SetClipAspectRatio(arg1:string,arg2:string):Promise<void>;

export function SetClipCaptionOpts(arg1:string,arg2:main.CaptionOpts):Promise<void>;

export function SetClipCaptionStyle(arg1:string,arg2:string):Promise<void>;

export function SetClipTrackOpts(arg1:string,arg2:main.TrackOpts):Promise<void>;

export function SetClipTrackTemplate(arg1:string,arg2:string):Promise<void>;

export function StartDownload(arg1:string):Promise<string>;

export function TestProviderKey(arg1:string,arg2:string):Promise<main.ProviderStatus>;

export function ToggleClip(arg1:string,arg2:boolean):Promise<void>;

export function UpdateClipTimestamp(arg1:string,arg2:number,arg3:number):Promise<void>;
